/**
 * PDF Export Utility for InvoiceHound
 * Generates invoice PDFs for download
 * 
 * In production, integrate with:
 * - PDFKit (Node.js) or Puppeteer (headless Chrome)
 * - Or use a service like jsPDF + html2canvas
 */

export interface InvoiceForPDF {
  invoiceNumber: string;
  clientName: string;
  freelancerName: string;
  freelancerEmail: string;
  issueDate: string;
  dueDate: string;
  lineItems: Array<{
    description: string;
    quantity: number;
    unitPrice: number;
  }>;
  subtotal: number;
  taxRate: number;
  total: number;
  currency: string;
  notes?: string;
}

/**
 * Generate a PDF invoice (mock implementation)
 * In production, this would use a real PDF library
 */
export const generateInvoicePDF = async (invoice: InvoiceForPDF) => {
  // Create HTML content for PDF
  const htmlContent = `
    <html>
      <head>
        <title>Invoice ${invoice.invoiceNumber}</title>
      </head>
      <body style="font-family: Arial, sans-serif; padding: 40px;">
        <h1>INVOICE</h1>
        <p><strong>Invoice #:</strong> ${invoice.invoiceNumber}</p>
        <p><strong>From:</strong> ${invoice.freelancerName}</p>
        <p><strong>Email:</strong> ${invoice.freelancerEmail}</p>
        <p><strong>To:</strong> ${invoice.clientName}</p>
        <p><strong>Issue Date:</strong> ${invoice.issueDate}</p>
        <p><strong>Due Date:</strong> ${invoice.dueDate}</p>
        
        <h2>Line Items</h2>
        <table border="1" cellpadding="10" style="width: 100%; margin-top: 20px;">
          <thead>
            <tr style="background-color: #f0f0f0;">
              <th>Description</th>
              <th>Quantity</th>
              <th>Unit Price</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            ${invoice.lineItems
              .map(
                (item) => `
            <tr>
              <td>${item.description}</td>
              <td>${item.quantity}</td>
              <td>${invoice.currency} $${item.unitPrice.toFixed(2)}</td>
              <td>${invoice.currency} $${(item.quantity * item.unitPrice).toFixed(2)}</td>
            </tr>
            `
              )
              .join("")}
          </tbody>
        </table>
        
        <div style="margin-top: 30px; text-align: right;">
          <p><strong>Subtotal:</strong> ${invoice.currency} $${invoice.subtotal.toFixed(2)}</p>
          <p><strong>Tax (${invoice.taxRate}%):</strong> ${invoice.currency} $${(
    invoice.subtotal *
    invoice.taxRate /
    100
  ).toFixed(2)}</p>
          <p style="font-size: 18px; font-weight: bold;">
            <strong>Total:</strong> ${invoice.currency} $${invoice.total.toFixed(2)}
          </p>
        </div>
        
        ${
          invoice.notes
            ? `<div style="margin-top: 30px; border-top: 1px solid #ccc; padding-top: 20px;">
          <h3>Notes</h3>
          <p>${invoice.notes}</p>
        </div>`
            : ""
        }
        
        <p style="margin-top: 50px; font-size: 12px; color: #666;">
          Generated by InvoiceHound
        </p>
      </body>
    </html>
  `;

  // For now, trigger a download with mock HTML
  // In production, use a real PDF library like PDFKit or jsPDF
  downloadFile(htmlContent, `invoice-${invoice.invoiceNumber}.html`, "text/html");
};

/**
 * Download a file to the client's computer
 */
export const downloadFile = (
  content: string,
  filename: string,
  contentType: string
) => {
  const element = document.createElement("a");
  element.setAttribute(
    "href",
    `data:${contentType};charset=utf-8,${encodeURIComponent(content)}`
  );
  element.setAttribute("download", filename);
  element.style.display = "none";

  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

/**
 * Export invoice as CSV
 */
export const exportInvoiceAsCSV = (invoice: InvoiceForPDF) => {
  const csvContent = [
    ["Invoice", invoice.invoiceNumber],
    ["From", invoice.freelancerName],
    ["To", invoice.clientName],
    ["Issue Date", invoice.issueDate],
    ["Due Date", invoice.dueDate],
    [],
    ["Description", "Quantity", "Unit Price", "Total"],
    ...invoice.lineItems.map((item) => [
      item.description,
      item.quantity.toString(),
      item.unitPrice.toString(),
      (item.quantity * item.unitPrice).toString(),
    ]),
    [],
    ["Subtotal", "", "", invoice.subtotal.toString()],
    [
      `Tax (${invoice.taxRate}%)`,
      "",
      "",
      ((invoice.subtotal * invoice.taxRate) / 100).toString(),
    ],
    ["Total", "", "", invoice.total.toString()],
  ]
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  downloadFile(csvContent, `invoice-${invoice.invoiceNumber}.csv`, "text/csv");
};

/**
 * Export invoice as JSON
 */
export const exportInvoiceAsJSON = (invoice: InvoiceForPDF) => {
  const jsonContent = JSON.stringify(invoice, null, 2);
  downloadFile(
    jsonContent,
    `invoice-${invoice.invoiceNumber}.json`,
    "application/json"
  );
};
